### ISSUE TITLE
Billing List

### ISSUE THREAD

**Issue by dawoodrizwan84** [SybringTeam/sybring_project#165]
Billing List
- Ändra "Billing" till "Expenses"
- Kolumnerna i listan som kan vara av intresse är: Datum, description, cost, Projekt, Action
- Under Ation finns Edit med. Men jag har tydligen inte rättighet att ändra.. Visst borde jag kunna ändra och komplettera?

**Comment by NatalieAktas** [comment]
Ändra "Billing" till "Expenses" -fixed
Kolumnerna i listan som kan vara av intresse är: Datum, description, cost, Projekt, Action - fixed
